### PR TITLE
[fix] Fix cleanup of old idea project files

### LINKED ISSUE #557: 0.51.0 breaks projects with root and one subproject name the same
I _think_ this is already being tracked by @iamdanfox per his comment here: https://github.com/palantir/gradle-baseline/pull/555#issuecomment-467837448, but filing formally.

### PR DESCRIPTION
**Pull request by dansanduleac**
## Before this PR

Regression introduced in #550 means that `.iml` files might be removed if the idea extension were configured in such a way as for them to differ from the project name.
Even if not explicitly configured, if a subproject had the same name as the root project, the IDEA plugin would give it a name like `${project.name}-${project.name}.iml` as mentioned in https://github.com/palantir/gradle-baseline/pull/555#issuecomment-467851332, which differs from the name the cleanup task was instructed to exclude.

## After this PR

Decide based on the outputs of the actual tasks creating these ipr / iws / iml files what the name that they would use is, and exclude just that name, rather than assuming it's going to be e.g. `${project.name}.iml`.

Fixes #557.

### CODE REVIEW

File: gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy [hunk 1]
```diff
@@ -53,26 +60,36 @@ class BaselineIdea extends AbstractBaselinePlugin {
...
-            moveProjectReferencesToEnd(ideaModuleModel);
+            markResourcesDirs(ideaModuleModel)
+            moveProjectReferencesToEnd(ideaModuleModel)
         }
 
         // If someone renames a project, leftover {ipr,iml,ipr} files may still exist on disk and
         // confuse users, so we proactively clean them up. Intentionally using an Action<Task> to allow up-to-dateness.
         Action<Task> cleanup = new Action<Task>() {
             void execute(Task t) {
+                if (t.project.rootProject == t.project) {
```
Comment (iamdanfox) [inline gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy:72]: Why do we still need this if you're accurately tracking the outputs of the idea task?

Comment (dansanduleac) [reply gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy:72]: the ipr and iws tasks only exist on the root project

Comment (dansanduleac) [reply gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy:72]: remember that this plugin is applied on all projects when you apply `com.palantir.baseline`

**Comment by iamdanfox** [comment]
:+1:

**Comment by gregakinman** [comment]
thanks!
