### PR TITLE
Fix GStringImpl cast to String issue in Eclipse plugin

### LINKED ISSUE #69: gradle eclipse issue with 2.14
getting the following error when trying to run gradle eclipse using 2.14. Any idea @uschi2000 ?

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dummyproject-api:eclipseClasspath'.
> org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String
```

### PR DESCRIPTION
**Pull request by qinfchen**
fixes https://github.com/palantir/gradle-baseline/issues/69

### CODE REVIEW

**Comment by qinfchen** [comment]
@uschi2000

File: gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineEclipseIntegrationTest.groovy [hunk 1]
```diff
@@ -20,7 +20,7 @@ import com.google.common.base.Charsets
 import com.google.common.io.Files
 import nebula.test.IntegrationSpec
 import nebula.test.functional.ExecutionResult
-import org.apache.commons.io.FileUtils
+import org.gradle.internal.impldep.org.apache.commons.io.FileUtils
```
Comment (uschi2000) [inline gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineEclipseIntegrationTest.groovy]: is this a 2.14-only class?

Comment (qinfchen) [inline gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineEclipseIntegrationTest.groovy]: They removed the dependency on `org.apache.commons.io.FileUtils` and added `org.gradle.internal.impldep.org.apache.commons.io.FileUtils` instead.

Comment (qinfchen) [inline gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineEclipseIntegrationTest.groovy]: should we pull in org.apache.commons.io.FileUtils? since it is for tests, i'd prefer pulling it directly

Comment (uschi2000) [inline gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineEclipseIntegrationTest.groovy]: yes, I was just going to suggest that. can we stay on gradle 2.13 for a bit too, please? (don't want people to upgrade unnecessarily often.)

**Comment by qinfchen** [comment]
ok, remove the gradle version in baseline. I think we should fix this regardless, so if people do decide to use new version of gradle, this plugin would still work

**Comment by uschi2000** [comment]
sorry, what exactly is broken against 2.14?

**Comment by qinfchen** [comment]
From the release note below, which broke the GStringImpl that we use in Eclipse plugin

```
A number of plugins were converted from Groovy to Java

The following plugins were fully converted to Java: jacoco, scala, osgi, javascript, distribution and announce.

Some other plugins were partially converted to Java, keeping tasks types as Groovy classes: init, checkstyle, codenarc, findbugs, pmd, jdepend, java, war, ear, application, signing, comparison, idea and eclipse. For the latter two, plugin types have also been kept in Groovy.

Existing builds and plugins should continue to work.

API method changes

org.gradle.api.artifacts.DependencyArtifact has setters for all properties to make it clearer that this type is mutable.
org.gradle.api.java.archives.ManifestMergeSpec now has setContentCharset() and getContentCharset() methods.
org.gradle.plugins.ide.eclipse.model.Facet.FacetType is no longer decorated with Groovy enum extensions.
org.gradle.testing.jacoco.plugins.JacocoTaskExtension.Output is no longer decorated with Groovy enum extensions.
org.gradle.nativeplatform.toolchain.plugins.MicrosoftVisualCppPlugin has been renamed to org.gradle.nativeplatform.toolchain.plugins.MicrosoftVisualCppCompilerPlugin.
org.gradle.testing.jacoco.plugins.JacocoPluginExtension.applyTo(JavaForkOptions) signature changed to make it clear this method accepts types that extend Task and JavaForkOptions.
```

**Comment by uschi2000** [comment]
ok, so with this PR merged the eclipse error should be fixed when using 2.14, correct?

**Comment by qinfchen** [comment]
yes, this plugin should work with 2.14 now.

**Comment by uschi2000** [comment]
cool, thanks

**Comment by qinfchen** [comment]
can we get a patch release out :)? Would love to use 2.14 and this hehe

**Comment by uschi2000** [comment]
done

**Comment by qinfchen** [comment]
👍 thanks!
