### PR TITLE
Exclude generated sources from error-prone

### LINKED ISSUE #1570: 3.57.1 breaks error-prone generated excluded paths
## What happened?

As seen in excavator bump PR https://github.com/palantir/tritium/pull/925 , the changes in https://github.com/palantir/gradle-baseline/pull/1568 do not seem to handle cases that previously were excluded such as `build/metricSchema/generated_src` used by `metric-schema` which is causing the baseline bump excavator on tritium to fail compilation: https://app.circleci.com/pipelines/github/palantir/tritium/906/workflows/7c65b97b-b475-46fc-a1e1-b5a4bf7198a0/jobs/11565

## What did you want to happen?

Baseline bump to successfully compile so that the 🤖 work while we eat 🦃

### PR DESCRIPTION
**Pull request by schlosna**
## Before this PR

As seen in excavator bump PR https://github.com/palantir/tritium/pull/925 , the changes in https://github.com/palantir/gradle-baseline/pull/1568 do not seem to handle cases that previously were excluded such as `build/metricSchema/generated_src` used by `metric-schema` which is causing the baseline bump excavator on tritium to fail compilation: https://app.circleci.com/pipelines/github/palantir/tritium/906/workflows/7c65b97b-b475-46fc-a1e1-b5a4bf7198a0/jobs/11565

## After this PR

==COMMIT_MSG==
Exclude generated sources from error-prone
==COMMIT_MSG==

Closes https://github.com/palantir/gradle-baseline/issues/1570

## Possible downsides?

Probably want some additional test cases.

### CODE REVIEW

**Review by iamdanfox — APPROVED** [review]
Ah thanks for rescuing this! I wanted to make those regexes really specific, because I figured there was a danger of someone defining a class `com.palantir.foundry.build.Whatever` and getting it unintentionally excluded - tests definitely worth it

File: gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java [hunk 1]
```diff
@@ -292,6 +286,12 @@ private static void configureErrorProneOptions(
         }
     }
 
+    static String excludedPathsRegex() {
+        // don't want backslashes on windows to break our regex
+        String separator = File.separator.contains("\\") ? Pattern.quote("\\") : File.separator;
+        return String.format(".*%s(build|generated_.*[sS]rc|src%sgenerated.*)%s.*", separator, separator, separator);
```
Comment (schlosna) [inline gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java:292]: @iamdanfox we might be able to remove `build` from regex here, or might want to constrain the pattern to avoid falsely matching say `com/foo/build/Bar.java`.

**Comment by robert3005** [comment]
~Just an FYI, had a project with generated sources in `build/generated-src/antlr/`. Going to change that to `_`.~  Womp, looks I am not following the pattern

File: gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java (hunk 1 above)
Comment (pkoenig10) [reply gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java:292]: Yeah this feels a bit dangerous. I'd suggest we do something like `build.*generated` since almost all code-gen plugins I've seen put source files on a path with a `generated` component.
