### PR TITLE
Fix versions.props handling of partially overlapping forces

### LINKED ISSUE #379: Duplicate key error when checking artifact versions
Given the following `versions.props`:
```
com.fasterxml.jackson.*:* = 2.9.6
com.fasterxml.jackson.datatype:jackson-datatype-jdk7 = 2.6.7
```

Running `checkBomConflict` will result in the following error:
```
Execution failed for task ':checkBomConflict'.
> Duplicate key com.fasterxml.jackson.*:*
```

This is because we do not supply a merging function to the map collector here:
https://github.com/palantir/gradle-baseline/blob/0.32.3/gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BomConflictCheckTask.java#L99

Many times these conflicts are indicative of a non-ideal version props, but in certain cases overriding specific subpackages is desired. Given the example above, the only alternative is to individually specify each of `com.fasterxml.jackson.core:*`, `com.fasterxml.jackson.databind:*`, etc.

Ideally we would have a way to identify the "more specific" version of a particular artifact. However it's probably reasonable to assume that a single artifact will never map to more than 2 entries. So it would be sufficient to resolve conflicts only if one of the entries exactly matches the artifact.

### PR DESCRIPTION
**Pull request by dansanduleac**
Fixes #379 properly

## Before this PR

In `checkBomConflict`, multiple forces from `versions.props` that match the same artifact would pick the longest force as the one that was "used".
This is not always the the one that nebula picks, because nebula just picks the last line that matches the artifact.

A similar mistake occurs in `checkNoUnusedPin` where _every_ force is individually treated as used if it matches even a single artifact, disregarding other forces in the file that might have overridden it.

## After this PR

* `checkBomConflict`: Resolve conflicts by associating an artifact with the last `versions.props` line that matches it.
* `checkNoUnusedPin`: when considering a resolved artifact, only treat the *last* matching force as used.

This now matches nebula's behaviour.

### CODE REVIEW

**Review by ferozco — APPROVED** [review]

**Comment by ferozco** [comment]
discussed offline, would like to see an additional test showing the previously broken behaviour

**Comment by dansanduleac** [comment]
@ferozco actually quite hard to make up a test for `checkBomConflict` that doesn't also end up with unused forces that get picked up by the other task.
In the meanwhile though, I noticed `checkNoUnusedPins` was also broken in a similar way.
Updated the description, fixed it and added tests for that ([here](https://github.com/palantir/gradle-baseline/pull/423/files#diff-1b3ac1518abcb74fddedc83185b367e8R196)).

As part of this, noticed the original test 'Version props conflict should succeed' was wrong! The first star force wasn't actually being used anywhere, so the new logic correctly marked it as unused. I therefore changed the test to use jackson and make sure the star force is also used.

File: gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineVersionsIntegrationTest.groovy [hunk 1]
```diff
@@ -97,9 +97,9 @@ class BaselineVersionsIntegrationTest  extends AbstractPluginTest {
         result
     }
 
-    def buildAndFailWith(String error) {
+    void buildAndFailWith(String error) {
         BuildResult result = with('checkVersionsProps', '--stacktrace').buildAndFail()
-        result.output.contains(error)
+        assert result.output.contains(error)
```
Comment (dansanduleac) [inline gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineVersionsIntegrationTest.groovy:102]: better error messages! groovy will actually destructure your command when you use assert, just like it does when putting boolean expressions in a `then:` / `expect:` block.

File: gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineVersionsIntegrationTest.groovy [hunk 2]
```diff
@@ -174,21 +175,42 @@ class BaselineVersionsIntegrationTest  extends AbstractPluginTest {
...
-        setupVersionsProps("com.google.guava:* = 22.0\ncom.google.guava:guava = 23.0")
-        buildFile << standardBuildFile(projectDir) + """
+        setupVersionsProps("""
+            com.fasterxml.jackson.*:* = 2.9.3
+            com.fasterxml.jackson.core:jackson-annotations = 2.9.5
+        """.stripIndent())
+        buildFile << standardBuildFile(projectDir)
+        buildFile << """
         dependencies {
-            compile 'com.google.guava:guava'
```
Comment (dansanduleac) [inline gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineVersionsIntegrationTest.groovy:185]: original test was failing with the newly corrected logic, because `com.google.guava:*` is not being used by any artifact.

**Comment by dansanduleac** [comment]
@ferozco had an even better idea of what we can do here.
To avoid PR inflation, I'll file an issue with the follow-up.
