### PR TITLE
Strict unused variable check

### LINKED ISSUE #818: Unused parameters should not compile
## What happened?

Currently, errorprone's exist UnusedVariable check will prevent you declaring _local_ variables or fields but never using them:

```
> Task :log-receiver:compileJava FAILED
/Volumes/git/log-receiver/log-receiver/src/main/java/com/palantir/logreceiver/LogReceiverServer.java:37: warning: [UnusedVariable] The local variable 'whoops' is never read.
        String whoops = "alsdjld";
               ^
    (see https://errorprone.info/bugpattern/UnusedVariable)
  Did you mean to remove this line?
```

HOWEVER, an arguably more pernicious problem is unused arguments to a method will not be flagged:

```java
public void deleteThingy(AuthHeader authHeader) { // 🌶 auth never checked!
    store.deleteThingy();
}
```

## What did you want to happen?

Baseline should prevent this foot gun. It seems that Eclipse and IntelliJ can flag mistakes like this, and it seems that [sonarlint](https://rules.sonarsource.com/java/tag/unused/RSPEC-1172) has a similar thing ([source code](https://github.com/SonarSource/sonar-java/blob/master/java-checks/src/main/java/org/sonar/java/checks/unused/UnusedMethodParameterCheck.java))... [gradle plugin here](https://gitlab.com/remal/gradle-plugins/blob/master/src%2Fmain%2Fkotlin%2Fname%2Fremal%2Fgradle_plugins%2Fplugins%2Fcode_quality%2Fsonar%2FSonarLintPlugin.kt)

### PR DESCRIPTION
**Pull request by ferozco**
Closes #818 
## After this PR
==COMMIT_MSG==
Correctly identify unused parameters in public methods
==COMMIT_MSG==

## Possible downsides?
N/A

### CODE REVIEW

**Comment by ferozco** [comment]
👍

**Comment by iamdanfox** [comment]
Problems encountered so far:

- interfaces
- -XepDisableWarningsInGeneratedCode doesn't stop _errors_ in generated code, so you get a ton of complaints about immutables.

File: baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/UnusedParameter.java [hunk 1]
```diff
@@ -0,0 +1,943 @@
...
+import java.util.Set;
+import java.util.concurrent.atomic.AtomicBoolean;
+import javax.annotation.Nullable;
+import javax.lang.model.element.ElementKind;
+import javax.lang.model.element.Modifier;
+import javax.lang.model.element.Name;
+
+/**
+ * Copy from {@Link UnusedVariable } except we consider all parameter for unused analysis.
+ * We removed the `onlyCheckForReassignments` filter
```
Comment (carterkozak) [inline baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/UnusedParameter.java]: Should this be named `StrictUnusedVariable`, if it checks variables beyond parameters?

File: baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/UnusedParameter.java [hunk 2]
```diff
@@ -0,0 +1,939 @@
...
+                    "org.openqa.selenium.support.FindBys");
+
+    /** The set of types exempting a type that is extending or implementing them. */
+    private static final ImmutableSet<String> EXEMPTING_SUPER_TYPES =
+            ImmutableSet.of(
+            );
+
+    /** The set of types exempting a field of type extending them. */
+    private static final ImmutableSet<String> EXEMPTING_FIELD_SUPER_TYPES =
+            ImmutableSet.of("org.junit.rules.TestRule");
```
Comment (carterkozak) [inline baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/UnusedParameter.java]: This should include java serialization magic methods, It's common to disallow deserialization by implementing `readObject` as a no-op.
https://docs.oracle.com/javase/8/docs/api/java/io/Serializable.html

File: baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/UnusedParameter.java [hunk 3]
```diff
@@ -0,0 +1,939 @@
...
+                    "serialVersionUID",
+                    // TAG fields are used by convention in Android apps.
+                    "TAG");
+
+    private static final ImmutableSet<Modifier> LOGGER_REQUIRED_MODIFIERS =
+            Sets.immutableEnumSet(Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL);
+
+    private static final ImmutableSet<String> LOGGER_TYPE_NAME = ImmutableSet.of("GoogleLogger");
+
+    private static final ImmutableSet<String> LOGGER_VAR_NAME = ImmutableSet.of("logger");
```
Comment (carterkozak) [inline baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/UnusedParameter.java]: include `log`?

File: baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/UnusedParameterTest.java [hunk 4]
```diff
@@ -0,0 +1,56 @@
...
+    public void ohno() {
+        compilationHelper.addSourceLines(
+                "Test.java",
+                "import java.util.Optional;",
+                "class Test {",
+                "  // BUG: Diagnostic contains: Unused",
+                "  public static void foo(String buggy) {",
+                "  }",
+                "}").doTest();
+    }
```
Comment (carterkozak) [inline baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/UnusedParameterTest.java]: Can we test that unused parameters of type `Void` don't trigger the check?

File: baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/UnusedParameter.java (hunk 3 above)
Comment (ferozco) [reply baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/UnusedParameter.java]: Actually, I think we want to remove this special case entirely since you'd like to avoid having unused loggers sitting around

File: baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictUnusedVariable.java [hunk 5]
```diff
@@ -0,0 +1,926 @@
...
+ * Copy from {@Link UnusedVariable } except we consider all parameter for unused analysis.
+ * We modified the `onlyCheckForReassignments` filter to exclude abstract methods, to check loggers
+ * */
+@AutoService(BugChecker.class)
+@BugPattern(
+        name = "StrictUnusedVariable",
+        altNames = {"unused", "StrictUnusedVariable"},
+        summary = "Unused.",
+        providesFix = REQUIRES_HUMAN_ATTENTION,
+        severity = ERROR,
```
Comment (iamdanfox) [inline baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictUnusedVariable.java]: I think we gotta put this at WARN otherwise we wreck immutables

**Review by iamdanfox — APPROVED** [review]

File: baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/UnusedParameter.java (hunk 2 above)
Comment (ferozco) [reply baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/UnusedParameter.java]: The rule will ignore any parameter prefixed with `unused` so you should be able to easily avoid getting hit.

In general, I'd like to avoid adding special casing so that its easy to keep the rule up to date

**Comment by schlosna** [comment]
Is this intended to handle the cause where an implementation of interface or overridden method does not use a method parameter?

This is failing on tritium in https://circleci.com/gh/palantir/tritium/3813 which at least some feel like false positives that I would not want to have to `@SuppressWarnings("StrictUnusedVariable")`

```
> Task :tritium-core:compileJava
/Volumes/git/tritium/tritium-core/src/main/java/com/palantir/tritium/event/NoOpInvocationEventHandler.java:46: warning: [StrictUnusedVariable] The parameter 'context' is never read.
    public void onFailure(@Nullable InvocationContext context, @Nonnull Throwable cause) {
                                                      ^
    (see https://errorprone.info/bugpattern/StrictUnusedVariable)
  Did you mean 'public void onFailure(@Nonnull Throwable cause) {'?
/Volumes/git/tritium/tritium-core/src/main/java/com/palantir/tritium/event/NoOpInvocationEventHandler.java:41: warning: [StrictUnusedVariable] The parameter 'result' is never read.
    public void onSuccess(@Nullable InvocationContext context, @Nullable Object result) {
                                                                                ^
    (see https://errorprone.info/bugpattern/StrictUnusedVariable)
  Did you mean 'public void onSuccess(@Nullable InvocationContext context) {'?
/Volumes/git/tritium/tritium-core/src/main/java/com/palantir/tritium/event/NoOpInvocationEventHandler.java:41: warning: [StrictUnusedVariable] The parameter 'context' is never read.
    public void onSuccess(@Nullable InvocationContext context, @Nullable Object result) {
                                                      ^
    (see https://errorprone.info/bugpattern/StrictUnusedVariable)
  Did you mean 'public void onSuccess(@Nullable Object result) {'?
/Volumes/git/tritium/tritium-core/src/main/java/com/palantir/tritium/event/NoOpInvocationEventHandler.java:46: warning: [StrictUnusedVariable] The parameter 'cause' is never read.
    public void onFailure(@Nullable InvocationContext context, @Nonnull Throwable cause) {
                                                                                  ^
    (see https://errorprone.info/bugpattern/StrictUnusedVariable)
  Did you mean 'public void onFailure(@Nullable InvocationContext context) {'?
error: warnings found and -Werror specified
1 error
4 warnings

> Task :tritium-core:compileJava FAILED

> Task :tritium-test:compileJava
/Volumes/git/tritium/tritium-test/src/main/java/com/palantir/tritium/test/TestImplementation.java:43: warning: [StrictUnusedVariable] The parameter 'string' is never read.
    public void multiArgumentMethod(String string, int count, Collection<String> foo) {
                                           ^
    (see https://errorprone.info/bugpattern/StrictUnusedVariable)
  Did you mean 'public void multiArgumentMethod(int count, Collection<String> foo) {'?
/Volumes/git/tritium/tritium-test/src/main/java/com/palantir/tritium/test/TestImplementation.java:43: warning: [StrictUnusedVariable] The parameter 'count' is never read.
    public void multiArgumentMethod(String string, int count, Collection<String> foo) {
                                                       ^
    (see https://errorprone.info/bugpattern/StrictUnusedVariable)
  Did you mean 'public void multiArgumentMethod(String string, Collection<String> foo) {'?
/Volumes/git/tritium/tritium-test/src/main/java/com/palantir/tritium/test/TestImplementation.java:43: warning: [StrictUnusedVariable] The parameter 'foo' is never read.
    public void multiArgumentMethod(String string, int count, Collection<String> foo) {
                                                                                 ^
    (see https://errorprone.info/bugpattern/StrictUnusedVariable)
  Did you mean 'public void multiArgumentMethod(String string, int count) {'?
error: warnings found and -Werror specified
1 error
3 warnings

> Task :tritium-test:compileJava FAILED

FAILURE: Build completed with 2 failures.
```

**Comment by iamdanfox** [comment]
Yes, we do want to flag those (as a particular goal is to catch people implementing conjure-defined interfaces that specify an AuthHeader, but the implementation fails to use it)

The recommended suppression in this case is to just rename the variables to have an `unused` prefix, as this is a bit less verbose than the whole @SuppressWarnings thing.

```diff
-    public void onFailure(@Nullable InvocationContext context, @Nonnull Throwable cause) {
+    public void onFailure(@Nullable InvocationContext unusedContext, @Nonnull Throwable unusedCause) {
```
