### PR TITLE
Fix: formatter no longer adds whitespace to blank lines

### LINKED ISSUE #799: Formatter adds whitespace to empty lines, failing checkstyle
## What happened?

Made empty lines contain whitespace, which had to be fixed manually
https://github.com/palantir/gradle-consistent-versions/pull/228/commits/78ac698bca98eb43fbc50686b2e1fe7b853b66a4

## What did you want to happen?

I expect that these lines be left alone.

### PR DESCRIPTION
**Pull request by dansanduleac**
## Before this PR

Formatter adds whitespace to blank lines in block/javadoc comments, failing checkstyle

## After this PR
==COMMIT_MSG==
Don't add whitespace to blank lines inside comments. Fixes #799
==COMMIT_MSG==

### CODE REVIEW

**Comment by dansanduleac** [comment]
I tried adding a test but couldn't get it to fail... so let's not merge yet

File: gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineFormat.java [hunk 1]
```diff
@@ -65,7 +66,7 @@ public void apply(Project project) {
                 Task spotlessJava = project.getTasks().getByName("spotlessJava");
                 Task spotlessApply = project.getTasks().getByName("spotlessApply");
                 if (eclipseFormattingEnabled(project) && !Files.exists(eclipseXml)) {
-                    spotlessJava.dependsOn(project.getTasks().findByPath(":baselineUpdateConfig"));
+                    spotlessJava.dependsOn(":baselineUpdateConfig");
```
Comment (dansanduleac) [inline gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineFormat.java:69]: this is just style - no need to resolve the actual task ourselves since dependsOn takes a string

File: gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineFormat.java [hunk 2]
```diff
@@ -52,11 +52,12 @@ public void apply(Project project) {
                 java.removeUnusedImports();
                 // use empty string to specify one group for all non-static imports
                 java.importOrder("");
-                java.trimTrailingWhitespace();
 
                 if (eclipseFormattingEnabled(project)) {
                     java.eclipse().configFile(project.file(eclipseXml.toString()));
                 }
+
+                java.trimTrailingWhitespace();
```
Comment (iamdanfox) [inline gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineFormat.java:60]: this is gonna be different in an IDE vs from gradlew??

Comment (dansanduleac) [reply gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineFormat.java:60]: Technically, but formatting from within Intellij didn't produce the whitespace. I suspect that's due to how IntelliJ automatically trims trailing whitespace upon saving.

**Review by iamdanfox — APPROVED** [review]
