### PR TITLE
fix #969: Implement error prone ReverseDnsLookup for unexpected reverse dns lookups

### LINKED ISSUE #969: error prone check to discourage InetSocketAddress.getHostName
## What happened?
InetSocketAddress.getHostName may do a reverse DNS lookup, which is a potentially unexpected network call.

## What did you want to happen?
We should provide a warning to discourage use which can be suppressed when when this behavior is acknowledged and desired.

### PR DESCRIPTION
**Pull request by carterkozak**
==COMMIT_MSG==
Implement error prone ReverseDnsLookup for unexpected reverse dns lookups

Calling address.getHostName may result in a DNS lookup which is a network request,
making the invocation significantly more expensive than expected depending on the
environment.
This check  is intended to be advisory - it's fine to
@SuppressWarnings("ReverseDnsLookup") in certain cases, but is usually not
recommended.
==COMMIT_MSG==

### CODE REVIEW

File: baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ReverseDnsLookup.java [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+
+@AutoService(BugChecker.class)
+@BugPattern(
+        name = "ReverseDnsLookup",
+        link = "https://github.com/palantir/gradle-baseline#baseline-error-prone-checks",
+        linkType = BugPattern.LinkType.CUSTOM,
+        severity = BugPattern.SeverityLevel.WARNING,
+        summary = "Calling address.getHostName may result in a DNS lookup which is a network request, making the "
+                + "invocation significantly more expensive than expected depending on the environment.\n"
+                + "This check  is intended to be advisory - it's fine to @SuppressWarnings(\"ReverseDnsLookup\") "
```
Comment (raiju) [inline baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ReverseDnsLookup.java]: Nit: double-space `check  is`

Comment (schlosna) [inline baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ReverseDnsLookup.java]:
```suggestion
                + "This check is intended to be advisory - it's fine to @SuppressWarnings(\"ReverseDnsLookup\") "
```

File: baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ReverseDnsLookup.java [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+import java.net.InetAddress;
+import java.net.InetSocketAddress;
+
+@AutoService(BugChecker.class)
+@BugPattern(
+        name = "ReverseDnsLookup",
+        link = "https://github.com/palantir/gradle-baseline#baseline-error-prone-checks",
+        linkType = BugPattern.LinkType.CUSTOM,
+        severity = BugPattern.SeverityLevel.WARNING,
+        summary = "Calling address.getHostName may result in a DNS lookup which is a network request, making the "
```
Comment (iamdanfox) [inline baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ReverseDnsLookup.java]:
```suggestion
        summary = "Calling address.getHostName may result in a reverse DNS lookup which is a network request, making the "
```

**Review by iamdanfox — APPROVED** [review]
