### PR TITLE
fix #1161: Add error prone LoggerEnclosingClass

### LINKED ISSUE #1161: Consider a check to validate slf4j LoggerFactory.getLogger(class) uses the enclosing class
## What happened?

Couldn't find expected logging because the logger was copied from another class without updating the target class name.

## What did you want to happen?

This should fail compilation and suggest the enclosing class name.

### PR DESCRIPTION
**Pull request by carterkozak**
Loggers created using getLogger(Class<?>) must reference their enclosing
class.

## After this PR
==COMMIT_MSG==
Add error prone LoggerEnclosingClass check. Loggers created using getLogger(Class<?>) must reference their enclosing class.
==COMMIT_MSG==

## Possible downsides?
It's possible there are unexpected usage patterns which may need to be suppressed.

### CODE REVIEW

File: baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/LoggerEnclosingClass.java [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+@BugPattern(
+        name = "LoggerEnclosingClass",
+        link = "https://github.com/palantir/gradle-baseline#baseline-error-prone-checks",
+        linkType = BugPattern.LinkType.CUSTOM,
+        providesFix = BugPattern.ProvidesFix.REQUIRES_HUMAN_ATTENTION,
+        severity = BugPattern.SeverityLevel.WARNING,
+        summary = "Loggers created using getLogger(Class<?>) must reference their enclosing class.")
+public final class LoggerEnclosingClass extends BugChecker implements BugChecker.VariableTreeMatcher {
+
+    private static final Matcher<ExpressionTree> getLoggerMatcher = MethodMatchers.staticMethod()
```
Comment (ferozco) [inline baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/LoggerEnclosingClass.java]:
```suggestion
    private static final Matcher<VariableTree> LOGGER = Matchers.allOf(
            Matchers.isField(),
            Matchers.isSameType(Logger.class),
            Matchers.variableInitializer(MethodMatchers.staticMethod()
                    .onClass(LoggerFactory.class.getName())
                    .named("getLogger")
                    .withParameters(Class.class.getName())));
```

**Comment by ferozco** [comment]
CI failure is unrelated, looks like `http://www.vogella.com/tutorials/JUnit/article.html` is dead :(

File: baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/LoggerEnclosingClass.java (hunk 1 above)
Comment (carterkozak) [reply baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/LoggerEnclosingClass.java]: Snazzy, I hadn't seen `Matchers.variableInitializer!

**Comment by carterkozak** [comment]
Removing the dead link here: https://github.com/palantir/gradle-baseline/pull/1164

**Review by ferozco — APPROVED** [review]
Looks great!

**Comment by carterkozak** [comment]
Thanks for the quick review :-)
